---
title: "Econ_hw_3"
author: "Sarah Rohlfing"
date: "5/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)

```


```{r}
hw3_data <- read.csv(here("data", "HW3_data.csv")) %>% 
  clean_names() 
  
```

```{r}
elec_longer <- pivot_longer(data =hw3_data,
                            cols = q_low_kwh:q_high_kwh,
                            names_to = "income_group",
                            values_to = "quantity_kwh")
```

```{r}

ggplot(data = elec_longer, aes(y = price_cents, x = quantity_kwh)) +
  geom_point() +
  geom_smooth(method =lm, se = FALSE) +
  facet_wrap( ~income_group)+
  labs(x = "kwH",
       y = "Price of kwH",
       title = "Demend for low and high income households")

```
```{r}
#hw3_data %>% 
#hw3_data$q_agg_sum = q_low_kwh + q_high_kwh

hw3_data$price_dollars <- hw3_data$price_cents/100
```


```{r}
low.income.lm <-lm(price_cents ~ q_low_kwh, data = hw3_data)
slope.low <- low.income.lm$coefficient[2]
intercept.low <- low.income.lm$coefficient[1]
vector_range <- seq(0, 160000, length.out = 19)
hw3_data$low_demand = slope.low*(vector_range) + intercept.low

ggplot(data = hw3_data, aes(y = price_cents, x = low_demand)) +
  geom_line() +
  labs(x = "kwH",
       y = "Price of kwH",
       title = "Demand for low income")

```
```{r}
high.income.lm <-lm(price_cents ~ q_high_kwh, data = hw3_data)
slope.high <- high.income.lm$coefficient[2]
intercept.high <- high.income.lm$coefficient[1]
hw3_data$high_demand = slope.high*(vector_range) + intercept.high

ggplot(data = hw3_data, aes(y = price_cents, x = high_demand)) +
  geom_line()+
  labs(x = "kwH",
       y = "Price of kwH",
       title = "Demand for high income")
```

```{r}
demand <- function(p, model){
  q <- (p - model$coefficients[1])/model$coefficients[2]
  q <- ifelse(q<0, 0, q)
  return(q)
}


```

```{r}
demand_ex <- demand(p= 10, model = low.income.lm) #(example: to find what demand function will output at price = 2)
```


```{r}
demand_agg <- function(p){
  q <- demand(p, low.income.lm) + demand(p, high.income.lm)
  return(q)
}
price = seq(0, 30, length.out = 100)
Qagg <- map(price, demand_agg) %>% unlist()
df<- tibble(Qagg = Qagg, price = price)

ggplot(data = df, aes(y = price, x = Qagg)) +
  geom_line()+
  labs(x = "kwH",
       y = "Price of kwH",
       title = "Aggregate Demand")
```


```{r}
q_star_agg <- demand_agg(p=10) # q_star_agg = 536,719 kwH
p_star_before_tax <- 10 #10 cents is p star
```

```{r}
# find slope for supply curve
mpc_slope = p_star_before_tax/q_star_agg # slope of supply curve = 1.86e-5

df$q_random <- seq(0, 80000, length.out = 100)

hw3_data$q_kwh_sum <- hw3_data$q_low_kwh + hw3_data$q_high_kwh


df$supply_lm <- mpc_slope * df$q_random


#df$mpc_prices = mpc_slope*(Qagg) 

ggplot(data = df, aes(y = price, x = supply_lm)) +
  geom_point()

```

```{r}
# $51/1 metric ton * 0.000453592 metric tons/1 lb = $.0231/lb *.85 lb/kwh = $0.01966/kwh
# $ 0.10 + $0.01966 = $0.12/kwh (marginal external cost/kwh)

tax <- function(scc){
  t <- scc * .000453592 * 0.85 * 100
  return(t)
}

tax(scc = 51)

mec_per_kwh <- 12 # <- marginal external cost in dollars
```



```{r}
CS <- function(p, model){
  q <- demand(p, model)
  cs <- 0.5*(model$coefficients[1] - p)*q
  return(cs)}

# CS_ex <- CS(p = 10, model = low.income.lm) to test low income consumer surplus

CS_agg <- function(p){
  cs <- CS(p,low.income.lm) + CS(p,high.income.lm)
  return(cs)}

agg_consumer_surplus <- CS_agg(p=10) # = 5298722
# convert to dollars
agg_cs_dollars <- agg_consumer_surplus/100 # = $52,987
```

```{r}
Supply_fun <- function(q){
  p <- q*mpc_slope
  return(p)
}

Supply_fun(q=500000) # about 10 cents, yay

PS <- function(p){
  ps <- 0.5 * p * q_star_agg #might be wrong! had: .5 * p/mpc_slope
  return(ps)}

PS_status_quo <- PS(p = 10) # = 2,683,597 cents producer surplus under status quo
#convert to dollars
PS_sq_dollars <- PS_status_quo/100 # = $26,836
```

```{r}
# find environmental damage costs under status quo

env_cost <- 2 # $0.01966 per kwh of env. damage
env_cost_sq <- (env_cost * q_star_agg)/100 # = $10,734.39 of env damage under status quo q_star of 536719 kwh
```

```{r}
# find consumer surplus for low income vs. high income
low_cs_sq <- CS(p = 10, model = low.income.lm) # 811243 with the status quo, convert to dollars
low_cs_sq_dollars <- low_cs_sq/100 # = $8,112

high_cs_sq <- CS(p = 10, model = high.income.lm) # 4487479 cents with status quo, convert to dollars
high_cs_sq_dollars <- high_cs_sq/100 # = $44,875

# High income has a much higher consumer surplus than low income. High income has a surplus of $36,763 higher than low income.
```

```{r}
# P = mQ + b 
# P = b - t + mQ
# low income bears all the burden

new_low_intercept <- function(scc)
  {low_int <- low.income.lm$coefficients[1]- tax(scc)
  return(low_int)}
new_low_intercept(scc = 51) #= 21.404 is new y-intercept for the low income demand curve

low_demand_tax <- function(p, scc){
  q <- (p - new_low_intercept(scc))/low.income.lm$coefficients[2]
  return(q)
}

# low_demand_tax(p = 10, scc = 51)

Q_demand_agg_tax <- function(p, scc){
  q <- low_demand_tax(p, scc) + demand(p, high.income.lm)
  return(q)
}
tax_51_q <- Q_demand_agg_tax( p = 10, scc = 51) # = 518875 kwh is the q star with scc = to 51

# reduction in kwh consumption from 536719 - 518875

536719-518875 # = 17844 kwh reduction with the new tax.
```


Find high income consumer surplus with the tax
```{r}
CS_tax_high <- CS(p = 12, model = high.income.lm) # = 3695177 cents
# convert to dollars
CS_tax_high_dollars <- CS_tax_high/100 # = $36952
# Originally was $44875
44875-36952 # = $7923 less in consumer surplus with the SCC = 51
```


```{r}
CS_low_income <- function(p, scc, model){
  q <- low_demand_tax(p, scc)
  cs <- 0.5*(new_low_intercept(scc) - p)*q
  return(cs)}

CS_tax_low <- CS_low_income(p = 10, scc = 51, model = low.income.lm) # = 590186
CS_tax_low_dollars <- CS_tax_low/100 #= $5902 in the new CS
#The difference in consumer surplus 
low_cs_sq_dollars - CS_tax_low_dollars # = $2210.57 less in consumer surplus

```


Find the Pruducer surplus with the added tax. need to go down from 10 by 2(the environmental cost). This way the entire tax revenue will be 4 * the new q star
```{r}
PS_tax <- (0.5* tax_51_q * 8)/100 # turning it into dollars

PS_difference <- PS_no_tax - PS_tax # = a difference of $6,081
```

```{r}
env_damage_w_tax <- (Q_demand_agg_tax(p = 10, scc = 51) * 2)/100 # = $10,377

env_difference <- env_dollars_total - env_damage_w_tax # = $357 of env damage saved with the new tax
```

Total tax rev
```{r}
tax_rev_51 <- (Q_demand_agg_tax(p = 10, scc = 51) * 4)/100 # = $20,755 of tax revenue (is this too high??? Sandy made it sound like it had to be 4 cents for the height of the tax revenue)
```

#5 
```{r}
# high = CS(function of tax and MEC) + pre tax rebate
# high tax rebate = q_high/(q_high + q_low) * tax rev(chages with scc)
# low = CS + pre tax rebate - [MEC * q_tax_51]
# low tax rebate = q_low/(q_high+q_low) * tax revenue
```

